import { Providers } from '@/components/Providers';
import { fonts } from '@/styles/fonts';
import type { Metadata } from 'next';

import '@/styles/globals.css';
import { ReactNode } from 'react';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

// see docs: https://fontawesome.com/docs/web/use-with/react/use-with
config.autoAddCss = false;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${fonts.cabin.variable} ${fonts.oswald.variable}`}
    >
      <body
        suppressHydrationWarning
        className="font-cabin bg-background text-base text-foreground"
      >
        <Providers>
          <div className="bg-gradient-radial to-primary/15 min-h-screen from-transparent from-80%">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
